### ISSUE TITLE
Lack of encoding prevents installation in Python 2.7

### ISSUE THREAD

**Issue by grutz** [guzmonne/meraki_api#1]
I know the library is marked as "Py3" but having Py2 support would be nice. Attempting to install via `pip install meraki_api` returns the following error for Python 2.7.13:

```
Collecting meraki_api
  Using cached meraki_api-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/06/pqrgsdl52011v1g49c5qr3100000gn/T/pip-build-bY85Tr/meraki-api/setup.py", line 8, in <module>
        from meraki_api import __version__
      File "meraki_api/__init__.py", line 54, in <module>
        from .__version__ import __title__, __description__, __url__, __version__
      File "meraki_api/__version__.py", line 10
    SyntaxError: Non-ASCII character '\xc3' in file meraki_api/__version__.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/06/pqrgsdl52011v1g49c5qr3100000gn/T/pip-build-bY85Tr/meraki-api/
```

Simply adding `# -*- coding: utf-8 -*-` to `setup.py` and `meraki_api/__version__.py` resolves this.

**Comment by guzmonne** [comment]
Nice. I'll update the code as soon as possible.
